sudo: false
language: ruby
rvm:
  - 2.5.1
before_install: gem install bundler -v 1.16.1
script: 'gem build href-scraper.gemspec && gem install href_scraper-*.gem && href_scraper --url https://github.com'
deploy:
  provider: rubygems
  api_key: $rubygems_api_key
